version: '3.7'

services:
  chronograf:
    image: quay.io/influxdb/chronograf:1.7.12
    container_name: chronograf
    command: ["chronograf", "--influxdb-url=http://influxdb:8086"]
    ports:
      - "8888:8888"

  influxdb:
    image: influxdb:1.7.6
    container_name: influxdb
    ports:
      - "8083:8083"
      # UDP
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influx:rw

  kapacitor:
    image: kapacitor:1.5.2
    container_name: kapacitor
    ports:
      - "9092:9092"
    volumes:
      - ./data/kapacitor:/var/lib/kapacitor:rw
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf
    links:
      - chronograf

  telegraf:
    image: telegraf:1.11.0
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    links:
      - influxdb
